# Site settings
title: Julia Schwarz
description: "Julia Schwarz portfolio and personal website"
baseurl: ""
url: ""
#baseurl: "http://staging.juliaschwarz.net"
#url: "http://staging.juliaschwarz.net"
twitter_username: julenka
github_username:  julenka

# Build settings
markdown: kramdown
permalink: pretty
