# Site settings
title: Julia Schwarz
description: "Julia Schwarz portfolio and personal website"
baseurl: "http://juliaschwarz.net"
url: "http://juliaschwarz.net"

# Build settings
markdown: kramdown
permalink: pretty
