# Site settings
title: Julia Schwarz
description: "Julia Schwarz portfolio and personal website"
baseurl: "https://staging.juliaschwarz.net"
url: "https://staging.juliaschwarz.net"
twitter_username: julenka
github_username:  julenka

# Build settings
markdown: kramdown
permalink: pretty
