# Site settings
title: Julia Schwarz
description: "Julia Schwarz portfolio and personal website"
baseurl: ""
url: ""
twitter_username: julenka
github_username:  julenka

# Build settings
markdown: kramdown
permalink: pretty
