# Site settings
title: Julia Schwarz
description: "Julia Schwarz portfolio and personal website"
baseurl: "https://julenka.github.io/"
url: "https://julenka.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
